### PR TITLE
Capital letter on FileItem Status

### PR DESCRIPTION
**Pull request by mateusmx**
Changing the label in the FileItem status to start with Capital letters.

### CODE REVIEW

**Comment by JinSSJ3** [comment]
Hey @mateusmx , thank you again, it looks better with capital letter. 🥳 

We are publishing a new version of dropzone-ui on npm tomorrow. We are including these new fixes alongside other enhancements we were working on. If you are using dropzone-ui in some project, we hope you can wait the new version and reinstall the package with these changes. 😃 
We'll notifyyou at the moment we publish the new version. 🚀 

Thank you again.

**Comment by mateusmx** [comment]
> 
Hey Jin first of all, thanks for such an amazing package, I've been struggling between react-dropzone ... pure dropzonejs and finally I got this package which is awesome ! Sure thing I'll wait for tomorrow's release to update what I have, still in development. Also would love to know if it's possible to make possible a functionality that instead of clicking the 'info' button in the bottom right corner, would be really nice that when 'hover' the fileItem element it show that info (success or error) since for us developers can be a bit obvious to 'click' in the info button ... but for the regular users might not be as obvious. 

Regards,

Pablo !

**Comment by JinSSJ3** [comment]
Thanks for your words Pablo. We are happy you find this package useful. 💯 
Totally agree with your suggestion. You can be sure we´ll add that feature very soon. 
I can´t promise it will appear in tomorrow's release, but I can asure you that it will be added in the following one, 👀 since it is a great improvement for usability. 🧑‍🎨

regards,

Jin

**Comment by JinSSJ3** [comment]
Hi Pablo, hope you are doing well.

Just to tell you that we just deployed 🚀  the new version of [@dropzone-ui/react](https://www.npmjs.com/package/@dropzone-ui/react) (v6.2.0) including your great fixes and suggestions. Any further suggestions or need help, you can always open an issue or PR.

regards,

Jin

**Comment by mateusmx** [comment]
Already installed and working pretty nice ! Once the page is finish I'll let you know so you can see how this great package is used :) 

Regards !

Working !

**Comment by JinSSJ3** [comment]
That's great!!!

Looking forward to hear soon about your project when finished 👀 😃
Happy coding! 💻  

best regards!

**Comment by JinSSJ3** [comment]
> > 
> 
> Hey Jin first of all, thanks for such an amazing package, I've been struggling between react-dropzone ... pure dropzonejs and finally I got this package which is awesome ! Sure thing I'll wait for tomorrow's release to update what I have, still in development. Also would love to know if it's possible to make possible a functionality that instead of clicking the 'info' button in the bottom right corner, would be really nice that when 'hover' the fileItem element it show that info (success or error) since for us developers can be a bit obvious to 'click' in the info button ... but for the regular users might not be as obvious.
> 
> Regards,
> 
> Pablo !

Hey Pablo, hope you are doing well

Just to tell you that thank you very much!. We released 🚀 version [6.3.6](https://www.npmjs.com/package/@dropzone-ui/react), wich includes your amazing suggestion about showing the info (success error, not valid) when user `hovers` the FileItem. Details can be read [here](https://github.com/dropzone-ui/react-dropzone/releases/tag/v6.3.6).

Hope you enjoy
Best regards,
Dropzone-ui team

**Comment by mateusmx** [comment]
Hey Jin.

This are awesome news ! As I said before awesome work !

Regards,

Pablo.

**Pull request merged**
